name: Advent of Code 2019

on:
  push:
    branches: [ main ]
    paths:
      - 'advent-of-code/2019/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/_puzzle-box.yaml
    with:
      challenge: aoc
      event: "2019"
    secrets:
      AOC_SESSION_COOKIE: ${{ secrets.AOC_SESSION_COOKIE }}
      