name: Everybody Codes story2

on:
  push:
    branches: [ main ]
    paths:
      - 'everybody.codes/story2/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/_puzzle-box.yaml
    with:
      challenge: ecd
      event: "story2"
    secrets:
      ECD_SESSION_COOKIE: ${{ secrets.ECD_SESSION_COOKIE }}
